name: CI

on:
  push:
    branches:
    - main
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [8, 11, 17, 21]
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Check the project
      if: ${{ matrix.java_version == '8' }}
      run: ./gradlew check
    - name: Test the project
      if: ${{ matrix.java_version != '8' }}
      run: ./gradlew test
